### NumPy Creating Arrays
#### Create a NumPy ndarray Object
##### NumPy is used to work with arrays. The array object in NumPy is called ndarray.
##### We can create a NumPy ndarray object by using the array() function.

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


#### Use a tuple to create a NumPy array:



In [2]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)


[1 2 3 4 5]


#### Dimensions in Arrays
##### A dimension in arrays is one level of array depth (nested arrays).
#### 0-D Arrays
##### 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [3]:
import numpy as np
arr = np.array(42)
print(arr)

42


#### 1-D Arrays
##### An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
##### These are the most common and basic arrays. 
##### Create a 1-D array containing the values 1,2,3,4,5:

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


#### 2-D Arrays
##### An array that has 1-D arrays as its elements is called a 2-D array.
##### These are often used to represent matrix or 2nd order tensors.
##### Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:



In [5]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


#### 3-D arrays
##### An array that has 2-D arrays (matrices) as its elements is called 3-D array.
##### These are often used to represent a 3rd order tensor.
##### Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:



In [6]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Check Number of Dimensions?
##### NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
##### Check how many dimensions the arrays have:



In [7]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


#### Higher Dimensional Arrays
##### An array can have any number of dimensions.
##### When the array is created, you can define the number of dimensions by using the ndmin argument.
##### Create an array with 5 dimensions and verify that it has 5 dimensions:



In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


#### NumPy Array Indexing
#### Access Array Elements
##### Array indexing is the same as accessing an array element.
##### You can access an array element by referring to its index number.
##### The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.
##### Get the first element from the following array:





In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])


1


#### Get the second element from the following array.



In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1])


2


#### Get third and fourth elements from the following array and add them.



In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])


7


#### Access 2-D Arrays
##### To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
##### Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.
##### Access the element on the first row, second column:



In [12]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2


#### Access the element on the 2nd row, 5th column:

In [13]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])


5th element on 2nd row:  10


#### Access 3-D Arrays
##### To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.
##### Access the third element of the second array of the first array:



In [16]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1,2])


6


#### Negative Indexing
##### Use negative indexing to access an array from the end.
##### Print the last element from the 2nd dim:





In [17]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


#### NumPy Array Slicing
#### Slicing arrays
Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].
If we don't pass start its considered 0
If we don't pass end its considered length of array in that dimension
If we don't pass step its considered 1
#### Slice elements from index 1 to index 5 from the following array:




In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


#### Slice elements from index 4 to the end of the array:



In [25]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])


[5 6 7]


#### Slice elements from the beginning to index 4 (not included):



In [23]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])


[1 2 3 4]


#### Negative Slicing
##### Use the minus operator to refer to an index from the end:
##### Slice from the index 3 from the end to index 1 from the end:



In [31]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])


[5 6]


#### STEP
##### Use the step value to determine the step of the slicing:
##### Return every other element from index 1 to index 5:



In [38]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])


[2 4]


#### Return every other element from the entire array:



In [45]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])


[1 3 5 7]


#### Slicing 2-D Arrays
##### From the second element, slice elements from index 1 to index 4 (not included):



In [48]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])


[7 8 9]


#### From both elements, return index 2:



In [53]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])


[3 8]


#### From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:



In [58]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,1:4])


[[2 3 4]
 [7 8 9]]


#### NumPy Array Shape
###### Shape of an Array
###### The shape of an array is the number of elements in each dimension.
###### Get the Shape of an Array
###### Print the shape of a 2-D array:

 

In [56]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


#### Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:



In [69]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#### NumPy Array Reshaping
#### Reshaping arrays
###### Reshaping means changing the shape of an array.
###### The shape of an array is the number of elements in each dimension.
###### By reshaping we can add or remove dimensions or change number of elements in each dimension.
### Reshape From 1-D to 2-D
###### Convert the following 1-D array with 12 elements into a 2-D array.
###### The outermost dimension will have 4 arrays, each with 3 elements:




In [73]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = arr.reshape(2, 3)
print(newarr)


[[1 2 3]
 [4 5 6]]


### Reshape From 1-D to 3-D
###### Convert the following 1-D array with 12 elements into a 3-D array.
###### The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:



In [78]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16,17,18])
newarr = arr.reshape(3, 3, 2)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


#### Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.
We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.
Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):



### Returns Copy or View?
##### Check if the returned array is a copy or a view:

In [65]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]


#### Unknown Dimension
###### You are allowed to have one "unknown" dimension.
###### Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
###### Pass -1 as the value, and NumPy will calculate this number for you.
#### Convert 1D array with 8 elements to 3D array with 2x2 elements:




In [92]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2,-1)
print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Flattening the arrays
###### Flattening array means converting a multidimensional array into a 1D array.
###### We can use reshape(-1) to do this.
###### Convert the array into a 1D array:



In [93]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]


### Random Numbers in NumPy
###### What is a Random Number?
###### Random number does NOT mean a different number every time. Random means something that can not be predicted logically.
### Generate Random Number
###### NumPy offers the random module to work with random numbers.
###### Generate a random integer from 0 to 100:






In [99]:
from numpy import random
x = random.randint(100)
print(x)


31


#### Generate Random Float
###### The random module's rand() method returns a random float between 0 and 1.
###### Generate a random float from 0 to 1:



In [103]:
from numpy import random
x = random.rand()
print(x)


0.9510321813648356


#### Generate Random Array
###### In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.
#### Integers
###### The randint() method takes a size parameter where you can specify the shape of an array.
###### Generate a 1-D array containing 5 random integers from 0 to 100:



In [106]:
from numpy import random
x=random.randint(100, size=(5))
print(x)


[95 16 50 44 97]


#### Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:



In [108]:
from numpy import random
x = random.randint(100, size=(3, 5))
print(x)


[[35 46 55 28 83]
 [39 59 68 91 91]
 [16 94 99 13 21]]


#### Floats
###### The rand() method also allows you to specify the shape of the array.
###### Generate a 1-D array containing 5 random floats:



In [110]:
from numpy import random
x = random.rand(5)
print(x)


[0.75310012 0.61109385 0.31146994 0.60902136 0.07672787]


#### Generate a 2-D array with 3 rows, each row containing 5 random numbers:



In [111]:
from numpy import random
x = random.rand(3, 5)
print(x)


[[0.35454511 0.32774966 0.48245327 0.07658348 0.50274868]
 [0.76575753 0.1612083  0.74672482 0.24467796 0.82616221]
 [0.38031347 0.17978217 0.05548846 0.55303615 0.21426189]]


#### Generate Random Number From Array
###### The choice() method allows you to generate a random value based on an array of values.
###### The choice() method takes an array as a parameter and randomly returns one of the values.
###### Return one of the values in an array:



In [116]:
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)


9


#### Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):



In [118]:
from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)



[[3 3 9 5 9]
 [5 5 9 3 5]
 [3 7 7 5 7]]
